# Generated by Django 6.0.2 on 2026-03-02 00:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('done', models.BooleanField(default=False)),
                ('House', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='housename',
        ),
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(related_name='house_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='request',
            field=models.ManyToManyField(related_name='house_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
