# Generated by Django 6.0.1 on 2026-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cleaning_task_rename_name_house_housename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning_task',
            name='start_week',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cleaning_task',
            name='user_added',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
