# Generated by Django 6.0.1 on 2026-03-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cleaning_task_start_week_cleaning_task_user_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cleaning_task',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
