# Generated by Django 6.0.1 on 2026-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_cleaning_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='House',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cleaning_task',
            name='done',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='cleaning_task',
            name='start_week',
            field=models.IntegerField(null=True),
        ),
    ]
