# Generated by Django 6.0.1 on 2026-03-05 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_cleaning_task_house_alter_cleaning_task_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
