# Generated by Django 6.0.1 on 2026-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_cleaning_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
