# Generated by Django 6.0.1 on 2026-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_cleaning_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='user_added',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
