# Generated by Django 6.0.2 on 2026-03-07 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_cleaning_task_user_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning_task',
            name='assigned_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
