# Generated by Django 6.0.2 on 2026-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_cleaning_task_assigned_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
