# Generated by Django 6.0.2 on 2026-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_cleaning_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_task',
            name='description',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
